### ISSUE TITLE
Configuration file

### ISSUE THREAD

**Issue by myselfpt** [microsoft/AmbariBasedHadoopExporter#15]
Hi, 

I'm trying to use this in a non-Azure, non-Kubernetes environment but I can't find the provided configuration file example (404).

Could you please re-upload it?

Thanks in advance

**Comment by SolomonTomer** [comment]
Hi,

Thanks for opening this ticket. I've fixed the problem, you can now access the link.

Thanks,
Tomer

**Comment by myselfpt** [comment]
@SolomonTomer 
Thank you! :)
